files:
  include: "**/*.scss"
  ignore: "test/**/*.scss"
options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes:
    - 1
    - include: true
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 1
    - convention: "0"
  brace-style:
    - 2
    - style: 1tbs
    - allow-single-line: false
  clean-import-paths:
    - 1
    - leading-underscore: false
    - filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 1
    - include: false
  empty-line-between-blocks:
    - 2
    - include: true
    - allow-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - convention: strictbem
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format: 0
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 1
    - length: 3000
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 5
  no-color-keywords: 2
  no-css-comments: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-misspelled-properties: 1
  no-trailing-zero: 2
  no-url-domains: 1
  no-url-protocols: 1
  one-declaration-per-line: 2
  quotes:
    - 1
    - style: single
  shorthand-values: 2
  space-after-colon: 2
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 1
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  zero-unit:
    - 2
    - include: false
