base: '/'
baseVariants:
  -
    base: 'http://localhost/'
    condition: 'getenv("IS_DOCKER") == "Docker"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Fluid
    errorFluidTemplate: 'fileadmin/lynx/ext/lynx/Templates/Sites/Error404.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
  -
    errorCode: 500
    errorHandler: Fluid
    errorFluidTemplate: 'fileadmin/lynx/ext/lynx/Templates/Sites/Error500.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
  -
    errorCode: 403
    errorHandler: PHP
    errorPhpClassFQCN: Swe\Lynx\ErrorHandling\ErrorHandling
  -
    errorCode: 503
    errorHandler: Fluid
    errorFluidTemplate: 'fileadmin/lynx/ext/lynx/Templates/Sites/Error503.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
  -
    errorCode: 0
    errorHandler: Fluid
    errorFluidTemplate: 'fileadmin/lynx/ext/lynx/Templates/Sites/AnyError.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
routeEnhancers:
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 5
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
rootPageId: 1
websiteTitle: 'Lynx'
