services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Swe\Lynx\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Swe\Lynx\EventListener\LynxInitialisation:
    public: true
    tags:
      - name: event.listener
        identifier: 'lynxInitialisationListener'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
