# Load default processing options
imports:
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
    config:
        contentsCss: '/fileadmin/lynx/scss/compiled/rte.css'

        style:
            definitions:
                - { name: 'Title H1', element: 'h1', classes: [], styles: {  } }
                - { name: 'Title H2', element: 'h2', classes: [], styles: {  } }
                - { name: 'Title H3', element: 'h3', classes: [], styles: {  } }
                - { name: 'Title H4', element: 'h4', classes: [], styles: {  } }
                - { name: 'Quote / Citation', element: 'blockquote', classes: [], styles: {  } }
                - { name: 'Code block', element: 'code', classes: [], styles: {  } }
                - { name: 'Yellow marker', element: 'span', classes: ['yellow'], styles: { background: 'yellow' } }

        heading:
            options:
                - { model: 'paragraph', title: 'Paragraph' }
                - { model: 'heading1', view: 'h1', title: 'Heading 1' }
                - { model: 'heading2', view: 'h2', title: 'Heading 2' }
                - { model: 'heading3', view: 'h3', title: 'Heading 3' }
                - { model: 'heading4', view: 'h4', title: 'Heading 4' }
                - { model: 'heading5', view: 'h5', title: 'Heading 5' }
                - { model: 'heading6', view: 'h6', title: 'Heading 6' }
                - { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }

        toolbar:
            items:
                - heading
                - style
                - '|'
                - undo
                - redo
                - '|'
                - horizontalLine
                - bold
                - italic
                - underline
                - strikethrough
                - subscript
                - superscript
                - alignment
                - removeFormat
                - Typo3Link
                - Typo3Unlink
                - '|'
                - bulletedList
                - numberedList
                - blockQuote
                - indent
                - outdent
                - '|'
                - findAndReplace
                - selectAll
                - clipboard
                - softHyphen
                - specialCharacters
                - '|'
                - sourceEditing
                #break - '-'
                #separator - '|'
                #- insertTable
                #- tableColumn
                #- tableRow
                #- mergeTableCells

        alignment:
            options:
                - { name: 'left', className: 'text-left' }
                - { name: 'center', className: 'text-center' }
                - { name: 'right', className: 'text-right' }
                - { name: 'justify', className: 'text-justify' }

# Allow s and u tag
processing:
    allowTags:
        - s
        - u

    ## Tags that are allowed outside of paragraphs
    allowTagsOutside: [address, article, aside, blockquote, figure, footer, header, hr, nav, section, div]

    ## allowed default attributes
    allowAttributes: [class, id, title, dir, lang, xml:lang, itemscope, itemtype, itemprop]

# Button config and defaults
buttons:
    link:
        relAttribute:
            enabled: false
        properties:
            class:
                allowedClasses: 'link,btn-primary,btn-next,btn-prev,btn-border,link-download,link-folder,link-external,link-external-blank,link-mail,link-tel'
        page:
            properties:
                class:
                    default: 'link'
        file:
            properties:
                class:
                    default: 'link-download'
        folder:
            properties:
                class:
                    default: 'link-folder'
        url:
            properties:
                class:
                    default: 'link-external'
        email:
            properties:
                class:
                    default: 'link-mail'
        telephone:
            properties:
                class:
                    default: 'link-tel'

# Classes config
classesAnchor:
    link:
        class: 'link'
        type: 'page'
        titleText: 'Normal'
    btn-primary:
        class: 'btn-primary'
        type: 'page'
        titleText: 'Button (Prim채r)'
    btn-next:
        class: 'btn-next'
        type: 'page'
        titleText: 'Button (Mehr)'
    btn-prev:
        class: 'btn-prev'
        type: 'page'
        titleText: 'Button (Zur체ck)'
    btn-border:
        class: 'btn-border'
        type: 'page'
        titleText: 'Button (Rahmen)'
    linkDownload:
        class: 'link-download'
        type: 'file'
    linkFolder:
        class: 'link-folder'
        type: 'folder'
    linkExternal:
        class: 'link-external'
        type: 'url'
    linkExternalBlank:
        class: 'link-external-blank'
        type: 'url'
        target: '_blank'
    linkMail:
        class: 'link-mail'
        type: 'email'
    linkTel:
        class: 'link-tel'
        type: 'telephone'

classes:
    link:
        name: 'Normal'
    btn-primary:
        name: 'Button (Prim채r)'
    btn-next:
        name: 'Button (Mehr)'
    btn-prev:
        name: 'Button (Zur체ck)'
    btn-border:
        name: 'Button (Rahmen)'
